# Generated by Django 2.2.6 on 2019-12-15 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of indicator', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the indicator', max_length=1000)),
                ('related', models.ManyToManyField(blank=True, related_name='_indicator_related_+', to='main.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular portfolio', primary_key=True, serialize=False)),
                ('weights', models.CharField(help_text='Enter an array that has sum = 1', max_length=200)),
                ('symbols', models.CharField(help_text='Enter a list of symbols', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of strategy', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the strategy', max_length=1000)),
                ('indicator', models.ManyToManyField(blank=True, to='main.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of theory', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the theory', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular strategy', primary_key=True, serialize=False)),
                ('kwarg', models.CharField(blank=True, help_text='Enter the dictionary containing indicator-related parameter', max_length=200, null=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular indicator', primary_key=True, serialize=False)),
                ('kwarg', models.CharField(blank=True, help_text='Enter the dictionary containing indicator-related parameter', max_length=200, null=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Indicator')),
            ],
        ),
    ]
