# Generated by Django 2.2.6 on 2019-10-21 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('name', models.CharField(help_text='Enter the name of indicator', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the indicator', max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular indicator', primary_key=True, serialize=False)),
                ('kwarg', models.CharField(blank=True, help_text='Enter the dictionary containing indicator-related parameter', max_length=200, null=True)),
                ('related', models.ManyToManyField(blank=True, related_name='_indicator_related_+', to='main.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('name', models.CharField(help_text='Enter the name of theory', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the theory', max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular theory', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('name', models.CharField(help_text='Enter the name of strategy', max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the strategy', max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular strategy', primary_key=True, serialize=False)),
                ('indicator', models.ManyToManyField(blank=True, to='main.Indicator')),
            ],
        ),
    ]
