# Generated by Django 2.2.6 on 2019-10-24 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191023_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='kwarg',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StrategyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular strategy', primary_key=True, serialize=False)),
                ('kwarg', models.CharField(blank=True, help_text='Enter the dictionary containing indicator-related parameter', max_length=200, null=True)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular indicator', primary_key=True, serialize=False)),
                ('kwarg', models.CharField(blank=True, help_text='Enter the dictionary containing indicator-related parameter', max_length=200, null=True)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Indicator')),
            ],
        ),
    ]
