# Generated by Django 2.2.6 on 2019-10-24 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191024_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular portfolio', primary_key=True, serialize=False)),
                ('weights', models.CharField(help_text='Enter an array that has sum = 1', max_length=200)),
                ('symbols', models.CharField(help_text='Enter a list of symbols', max_length=200)),
            ],
        ),
    ]
